name = "jiwonz/luau_disk"
version = "0.1.2"
description = "Immutable data structures for Lua by jeparlefrancais, Uploaded for pesde"
authors = ["jeparlefrancais <jeparlefrancais21@gmail.com>"]
repository = "https://github.com/seaofvoices/luau-disk"
license = "MIT"
includes = ["src", "pesde.toml", "LICENSE.txt", "README.md"]

[target]
environment = "luau"
lib = "src/init.luau"

[indices]
default = "https://github.com/pesde-pkg/index"
